data:
  augment: true
  batch_size: 12
  data_root: ./DATA
  dataset_type: UIEB
  img_size: 256
  num_workers: 4
  preprocessing_type: waternet
device: cuda
exp_dir: experiments/underwater_diffusion_v1
exp_name: underwater_diffusion_light
logging:
  log_dir: logs
  use_wandb: false
  wandb_project: underwater-enhancement
loss:
  adversarial_weight: 0.1
  structure_weight: 1.0
  underwater_weight: 0.5
  use_adversarial: false
model:
  base_channels: 64
  img_size: 256
  in_channels: 3
  latent_channels: 4
  physics_dim: 64
  time_steps: 500
seed: 42
testing:
  eta: 0.0
  num_steps: 20
  use_ddim: true
training:
  diffusion_lr: 0.0001
  grad_clip: 1.0
  log_freq: 100
  max_val_batches: 50
  min_lr: 1.0e-06
  num_epochs: 1000
  save_freq: 10
  vae_lr: 0.0001
  val_freq: 1000
  weight_decay: 1.0e-05
